### ISSUE TITLE
The prometheus alerting doesn't work.

### ISSUE THREAD

**Issue by guiadco** [actiniumio/allspark#124]
---
### Describe the bug

The prometheus alerting doesn't work.
The docker container have a restarting status

---
### Reproduction scenario

Steps to reproduce the behaviour:

1. Launch the playbook
2. Look logs

```
level=info ts=2018-10-14T16:02:52.561389503Z caller=main.go:174 msg="Starting Alertmanager" version="(version=0.15.2, branch=HEAD, revision=d19fae3bae451940b8470abb680cfdd59bfa7cfa)"
level=info ts=2018-10-14T16:02:52.561443498Z caller=main.go:175 build_context="(go=go1.10.3, user=root@3101e5b68a55, date=20180814-10:53:39)"
level=info ts=2018-10-14T16:02:52.571177915Z caller=cluster.go:155 component=cluster msg="setting advertise address explicitly" addr=172.18.0.14 port=9094
level=info ts=2018-10-14T16:02:52.577627486Z caller=main.go:322 msg="Loading configuration file" file=alertmanager.yml
level=error ts=2018-10-14T16:02:52.579763124Z caller=main.go:325 msg="Loading configuration file failed" file=alertmanager.yml err="root route must specify a default receiver"
```

---
### Expected behaviour

> A clear and concise description of what you expected to happen.

---
### Allspark informations

> Informations about the control and allspark machines.

- **Allspark**
  - *version*

```
dfe7faf3bea837244fff761985fee2633049533f
```

  - *configuration*

```yaml
---
# defaults file for allspark

allspark_root_domain: mydomainname
allspark_root_directory: /opt/allspark
allspark_backup_directory: /opt/allspark/backup
allspark_admin_user: admin

allspark_docker_version: "18.06.0"

allspark_ldap:
  enabled: false
  organization: Allspark

allspark_monitoring:
  enabled: true

allspark_haproxy:
  ssl:
    enabled: true
    # If SSL is enabled, you can set the directory from which
    # endpoints certificates will be imported with this variable.
    # Files in the local directory should be PEM formatted certificates
    # named like their endpoint (e.g: `infra.allspark.localhost.pem`)
    certificates_directory:
    # If selfsigned certificates are enabled, any certificate missing
    # for an endpoint will be created on the fly.
    # If selfsigned is disabled and a certificate is missing, the
    # install won't be able to complete successfully.
    selfsigned:
      enabled: true
      # For example country: FR
      country: FR
      state: Haute-Garonne
      location: Toulouse
      organisation: xx
      organizational_unit: xxx


allspark_rocketchat:
  enabled: false

allspark_gitlab:
  enabled: true
  with_runner: true
  lfs_enabled: true

allspark_jenkins:
  enabled: true
  # Toggle default plugin import from release.
  import_plugins: true

allspark_sonarqube:
  enabled: true

allspark_backup:
  image: blacklabelops/volumerize

allspark_mattermost:
  enabled: true

allspark_portainer:
  enabled: true

### Release configuration
# Should not be here
allspark_release_tmp_directory: /opt/allspark/release
allspark_release_destination: /opt/allspark.tar.gz

```

- **Control machine**
  - *Operating system* :

```
Linux packer.allspark.localhost 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

  - *Ansible version* :

```
ansible 2.7.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/allspark/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```
