### ISSUE TITLE
Righ Bug /opt/allspark/config not writable

### ISSUE THREAD

**Issue by guiadco** [actiniumio/allspark#125]
---
### Describe the bug

```
TASK [pip : send [Pip] Requirements to remote server] *************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "checksum": "bd23a0cbc3b2cba34c896efb201dabf5919eabea", "msg": "Destination /opt/allspark/config not writable"}
        to retry, use: --limit @/home/allspark/allspark/install.retry

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=13   changed=0    unreachable=0    failed=1

[allspark@packer allspark]$ ll /opt/allspark/
total 0
drwxr-xr-x. 3 root     root     24 Oct 14 18:23 config
```

---
### Reproduction scenario

> **note**: You might want to use the Vagrant environment to create a reproducible scenario triggering the bug.

Steps to reproduce the behaviour:

1. sudo rm -rf /opt/allspark
2. Relaunch playbook install

---
### Expected behaviour

Functionnal Install
---
### Allspark informations

> Informations about the control and allspark machines.

- **Allspark**
  - *version*

```
dfe7faf3bea837244fff761985fee2633049533f
```

  - *configuration*

```yaml
---
# defaults file for allspark

allspark_root_domain: mydomainname
allspark_root_directory: /opt/allspark
allspark_backup_directory: /opt/allspark/backup
allspark_admin_user: admin

allspark_docker_version: "18.06.0"

allspark_ldap:
  enabled: false
  organization: Allspark

allspark_monitoring:
  enabled: true

allspark_haproxy:
  ssl:
    enabled: true
    # If SSL is enabled, you can set the directory from which
    # endpoints certificates will be imported with this variable.
    # Files in the local directory should be PEM formatted certificates
    # named like their endpoint (e.g: `infra.allspark.localhost.pem`)
    certificates_directory:
    # If selfsigned certificates are enabled, any certificate missing
    # for an endpoint will be created on the fly.
    # If selfsigned is disabled and a certificate is missing, the
    # install won't be able to complete successfully.
    selfsigned:
      enabled: true
      # For example country: FR
      country: FR
      state: Haute-Garonne
      location: Toulouse
      organisation: xx
      organizational_unit: xxx


allspark_rocketchat:
  enabled: false

allspark_gitlab:
  enabled: true
  with_runner: true
  lfs_enabled: true

allspark_jenkins:
  enabled: true
  # Toggle default plugin import from release.
  import_plugins: true

allspark_sonarqube:
  enabled: true

allspark_backup:
  image: blacklabelops/volumerize

allspark_mattermost:
  enabled: true

allspark_portainer:
  enabled: true

### Release configuration
# Should not be here
allspark_release_tmp_directory: /opt/allspark/release
allspark_release_destination: /opt/allspark.tar.gz

```

- **Control machine**
  - *Operating system* :

```
Linux packer.allspark.localhost 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

  - *Ansible version* :

```
ansible 2.7.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/allspark/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

**Comment by guiadco** [comment]
RM again and relaunch OK

**Comment by guiadco** [comment]
```yaml

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=216  changed=84   unreachable=0    failed=0

[allspark@packer allspark]$ ll /opt/allspark/
total 0
drwxr-----. 7 allspark allspark 132 Oct 14 18:30 config
drwxr-----. 4 allspark allspark  32 Oct 14 18:28 data
[allspark@packer allspark]$ ll /opt/allspark/config/
total 84
-rw-rw-r--. 1 allspark allspark 79590 Oct 14 18:29 gitlab.rb
drwxrwxr-x. 3 allspark allspark    66 Oct 14 18:29 grafana
drwxrwxr-x. 2 allspark allspark    45 Oct 14 18:29 haproxy
drwxrwxr-x. 3 allspark allspark    50 Oct 14 18:30 jenkins
drwxrwxr-x. 2 allspark allspark    46 Oct 14 18:29 mattermost
-rw-rw-r--. 1 allspark allspark    33 Oct 14 18:28 pip-requirements.txt
drwxrwxr-x. 2 allspark allspark    52 Oct 14 18:29 prometheus
```

**Comment by guiadco** [comment]
Need to add fix to pip role

```
- name: allspark_root_directory creation
  file:
    state: directory
    path: "{{ allspark_root_directory }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0740
  become: yes

- name: allspark data/config directory creation
  file:
    state: directory
    path: "{{ allspark_root_directory }}/{{item}}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0740
  with_items:
    - config
    - data

- name: allspark secrets directory creation
  file:
    state: directory
    path: "{{ allspark_root_directory }}/{{item}}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0700
  with_items:
    - data/secrets
```
